# https://docs.codecov.io/docs/common-recipe-list
# https://docs.codecov.io/docs/commit-status#patch-status

coverage:
  status:
    project:
      default:
        #target: 85%    # the required coverage value
        threshold: 3%  # the leniency in hitting the target
