# Docker build file for mqttwarn, with Slack SDK.
#
# Invoke like:
#
#   docker build --tag=mqttwarn-slack --file=Dockerfile.mqttwarn-slack .
#

# Derive from upstream image.
FROM ghcr.io/mqtt-tools/mqttwarn-standard:latest

# Make package installation run as "root" user
USER root

# Install Slack SDK.
RUN pip install wheel
RUN pip install mqttwarn[slack]

# Make process run as "mqttwarn" user
USER mqttwarn
