# Stage Docker images through GitHub Actions (GHA) to GitHub Container Registry (GHCR).
#
# Derived from:
# https://github.com/crate/cratedb-prometheus-adapter/blob/main/.github/workflows/release.yml
name: Release Docker Standard

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 10 * * *' # everyday at 10am

  # Allow job to be triggered manually.
  workflow_dispatch:

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

# The name for the produced image at ghcr.io.
env:
  GHCR_IMAGE_NAME: jpmens/mqttwarn-standard

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Acquire sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # List of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}
          # Generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Inspect meta
        run: |
          echo "Tags:      ${{ steps.meta.outputs.tags }}"
          echo "Labels:    ${{ steps.meta.outputs.labels }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-standard
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache-standard
          cache-to: type=local,dest=/tmp/.buildx-cache-standard-new

      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-standard
          mv /tmp/.buildx-cache-standard-new /tmp/.buildx-cache-standard

      - name: Display git status
        run: |
          set -x
          git describe
          git status
